### ISSUE TITLE
Improve the error messages reported back to the user

### ISSUE THREAD

**Issue by paalka** [UNINETT/appstore#12]
Currently some errors are passed directly back from tiller, and are thus rather verbose. We should provide custom error messages that provide information about what the user can do in order to fix these errors.

**Comment by gurvindersingh** [comment]
I tried creating a pod in a namespace where request resources was enough but not limit. So the depoyment went through but it was not able to start the pod due to quota exceeding. This error message was given only in the events. So we should really watch those events during deployment and if there is any error message we should display that back to user.. even we can show most of them if we want to show the progress of deployment.

**Comment by paalka** [comment]
Closing, as the addition of events in the status, as well as the introduction of a new «failing» status code has improved this quiet a bit.
